services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  backend:
    build: ./back-end
    container_name: backend
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_NAME_TEST=${DB_NAME_TEST}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_in=1d
      - NODE_env=production
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-networks

  frontend:
    build: ./front-end/Cinebook
    container_name: frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - app-networks

  nginx:
    build: ./nginx
    container_name: nginx-container
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-networks
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:

networks:
  app-networks:
    driver: bridge
