services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cinebook
      MYSQL_USER: app
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-networks

    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
      

  backend:
    build: ./back-end
    container_name: backend
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=app
      - DB_PASSWORD=123456
      - DB_NAME=cinebook
      - DB_NAME_TEST=cinebookTest
      - JWT_SECRET= CINEBOOKTOP
      - JWT_EXPIRES_in=1d
      - NODE_env=production
    ports:
    - 3000:3000
    depends_on:
      database:
          condition: service_healthy
    networks:
      - app-networks

  frontend:
    build: ./front-end/Cinebook
    container_name: frontend
    environment:
      - VITE_API_URL=/api/
    depends_on:
      - backend
    ports:
      - 5173:5173
    networks:
      - app-networks
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-networks

networks:
  app-networks:
volumes:
  db_data: