version: "3.8"

services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cinebook
      MYSQL_USER: app
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  backend:
    build: ./back-end
    container_name: backend
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=app
      - DB_PASSWORD=123456
      - DB_NAME=cinebook
      - DB_NAME_TEST=cinebookTest
      - JWT_SECRET=CINEBOOKTOP
      - JWT_EXPIRES_in=1d
      - NODE_env=production
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-networks

  frontend:
    build: ./front-end/Cinebook
    container_name: frontend
    environment:
      - VITE_API_URL=https://cinebook.local/api/
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - app-networks

  nginx:
    build: ./nginx
    container_name: nginx-container
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-networks
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:

networks:
  app-networks:
    driver: bridge
